[package]
name = "pd-vm-compiler"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
vm = { package = "pd-vm", git = "https://github.com/rustscript-lang/rustscript", rev = "b3b481ef9ce72d07763ae6911746ae0c06b19228", default-features = false, features = ["runtime", "edge-abi"] }
